import React, { useContext } from 'react';
import { useParams, Link } from 'react-router-dom';
import { CartContext } from '../context/CartContext';
import Zoom from 'react-medium-image-zoom';
import 'react-medium-image-zoom/dist/styles.css';
const products = [
  { id: 1, name: '2 Piece Luxury Plain Velvet Curtain-GREY', price: '4,899', image: 'https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/1st.webp?alt=media&token=21285bc4-3962-42ea-8a01-bf66c2eb5edc', description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.' },
  { id: 2, name: '2 Piece Luxury Plain Velvet Curtain', price: '4,899', image: 'https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/2.webp?alt=media&token=8b158f4b-794f-4f66-9d61-b6f07a6d8a70', description: 'This two-piece set of luxuriously soft velvet curtains is perfect for adding a touch of elegance to any home. The timeless beige colour of the curtains lends itself to any décor while providing the perfect amount of light filtering. The velvet fabric is durable and easy to care for.' },
  { id: 3, name: '2 Piece Luxury Plain Velvet Curtain-Navy Blue', price: '4,899', image: 'https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/3%20(2).webp?alt=media&token=e88fc50d-d2f8-4071-82cd-01d99c391336', description: 'This Luxury Plain Velvet Curtain in Navy blue brings elegance and sophistication to any room. Its made of smooth velvet material with an eye-catching plain design. Durable and luxurious, this curtain offers a timeless look that will last for years' },
  { id: 4, name: '2 PIECE OF PREMIUM VELVET CURTAINS BORDER DESIGN (GREY & OFFWHITE)', price: '6,499', image: 'https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/4.jpg?alt=media&token=18abe250-a7da-45cb-9037-cb168b0f0e4e', description: '90 Inches Long Size: 51×90″ (4.25×7.5 feet) 1 Pair. Super Velvet Curtain with design on top and on the belt.   Heavy Luxury Velvet Fabric Embroidered' },
  { id: 5, name: 'Luxury Velvet Curtains Grey & Cream LEC-136', price: '4,899', image: 'https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/5.webp?alt=media&token=bf469b38-d058-4ec7-830a-f8de6e3cfd9a', description: 'Premium Velvet Fabric. Experience the opulence of Luxury Velvet Curtains Grey & Cream LEC-136. Made from luxurious velvet for a rich, regal look and feel, these curtains feature a subtle grey and golden hue that adds a touch of sophistication to any home.' },
  { id: 6, name: 'Luxury Embossed Velvet Curtains (2 Panels with 2 belts) Beige LEC-103', price: '6,989', image: 'https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/6.jpg?alt=media&token=8249238c-23c3-4740-a0b9-2615a40603a6', description: 'Premium Velvet Fabric. Experience the opulence of Luxury Velvet Curtains Grey & Cream LEC-136. Made from luxurious velvet for a rich, regal look and feel, these curtains feature a subtle grey and golden hue that adds a touch of sophistication to any home.' },
  { "id": 7, "name": "2 Piece Luxury Plain Velvet Curtain-Black", "price": "4899", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/7.webp?alt=media&token=6c8f4905-5b00-4b61-b0c8-d4cfa447312d", description: 'Size: 51×90″ (4.25×7.5 feet) each curtain With 2 belts Fabric: Premium Velvet Fabric esigned to give any space a luxurious look, our premium Velvet Blackout Curtains, are the ideal of elegance and functionality. Crafted from high-quality velvet fabric, these curtains provide a timeless charm while offering exceptional light-blocking capabilities.'  },
  { "id": 8, "name": "2 Piece Luxury Plain Velvet Curtain-Black", "price": "5499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/8.webp?alt=media&token=4e0dd3d9-2b9c-4f61-af2f-27670684615d" , description: 'Size: 51×90″ (4.25×7.5 feet) each curtain with 2 Belts.  Fabric: Premium Velvet Fabric This luxury velvet curtain is the perfect addition to any décor. Completely black, the velvet fabric is sumptuous and will provide excellent insulation, ensuring your rooms remain cozy. With a timeless aesthetic, this curtain will never go out of style.'  },
  { "id": 9, "name": "2 PCS LUXURY VELVET EMBROIDERED CURTAINS(DOUBLE SHADED)", "price": "7,499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/9.webp?alt=media&token=7a1065b4-6bea-4315-b13a-c0ffb317778f" , description: '51×90″ (4.25×7.5 feet) each curtain Central Luxury Embossed With 2 folding belts'  },
  { "id": 10, "name": "2 Piece Luxury Plain Velvet Curtain-Golden", "price": "4899", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/10.webp?alt=media&token=3fe40713-ba9f-4ef3-810f-792fc0a9c88c", description: ' 90 Inches Long  Size: 51×90″ (4.25×7.5 feet)  1 Pair. Super Velvet Curtain with design on top and on the belt.  Heavy Luxury Velvet Fabric Embroidered'  },
  { "id": 11, "name": "Luxury Velvet Embroidered Curtains..", "price": "5999", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/11.webp?alt=media&token=5372d3e7-61e9-4b04-8aa9-40e4d0f954ea" , description: 'Machine wash in cold water, tumble dry low, and iron when needed. Cotton Percale Fabric 250 Thread Count The size of each panel is 52"x 90"'  },
  { "id": 12, "name": "Luxury Velvet Splendid Curtains Blackout Black & White LEC-126", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/12.webp?alt=media&token=737cecb7-dc1d-4d07-9d32-846789b714e0" , description: 'Machine wash in cold water, tumble dry low, and iron when needed.  Cotton Percale Fabric 250 Thread Count The size of each panel is 52"x 90"'  },
  { "id": 13, "name": "2 Panels Luxury Velvet Embroidered Curtains With 2 Belts (Gray & Black)", "price": "6489", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/13.webp?alt=media&token=0d12475c-902b-4b81-a86f-c87889dc6719" , description: 'Premium Velvet Fabric Introducing our 2 Piece Luxury Plain Velvet Curtain-Golden. Made with premium velvet fabric, these curtains provide outstanding insulation, noise reduction and blackout capabilities for any room. The golden color adds a subtle elegance to any home. Perfect for any decor.'  },
  { "id": 14, "name": "2 Panels Luxury Velvet Embroidered Curtains With 2 Belts(Maroon & White)", "price": "6489", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/14.webp?alt=media&token=2d8e76fa-d51a-4063-87b6-070b69611168"  , description: 'Premium Velvet Fabric Experience the opulence of Luxury Velvet Curtains Grey & Maroon LEC-134. Made from luxurious velvet for a rich, regal look and feel, these curtains feature a subtle grey and golden hue that adds a touch of sophistication to any home' },
  { "id": 15, "name": "Luxury Velvet Splendid Curtains Blackout – Light Golden & Black LEC-131", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/15.webp?alt=media&token=f99fdf45-4fe5-4dd8-8973-acf9e56f5d57" , description: 'Premium Velvet Fabric This two-piece luxury curtain made from maroon velvet is the perfect addition to any room. The soft material will add a touch of elegance and style to your home. The curtains are designed with a timeless look, making them a lasting decor choice.' },
  { "id": 16, "name": "Luxury Velvet Curtains Grey & Maroon LEC-134", "price": "4899", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/16.webp?alt=media&token=31915bb3-8e19-429f-9c46-8fdb585742d7" , description: 'Velvet 51×90″ (4.25×7.5 feet) each curtain With 2 folding belts This Luxury Plain Velvet Curtain in green brings elegance and sophistication to any room. Its made of smooth velvet material with an eye-catching plain design. Durable and luxurious, this curtain offers a timeless look that will last for years' },
  { "id": 17, "name": "2 Piece Luxury Plain Velvet Curtain-Maroon", "price": "4899", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/17.webp?alt=media&token=7d6bdfe4-9931-4950-80ff-59582b5b3c1e"  , description: 'Size: 51×90″ (4.25×7.5 feet) each curtain   Fabric: Premium Velvet Fabric Experience the opulence of Luxury Velvet Curtains Grey & Blue LEC-135. Made from luxurious velvet for a rich  regal look and feel, these curtains feature a subtle grey and golden hue that adds a touch of sophistication to any home.'},
  { "id": 18, "name": "2 Piece Luxury Plain Velvet Curtain-Green", "price": "4899", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/18.webp?alt=media&token=ccd53b08-844e-4b9d-abac-0840bdc10152"  , description: 'Size: 51×90″ (4.25×7.5 feet) each curtain Fabric: Premium Velvet Fabric  Experience the opulence of Luxury Velvet Curtains Grey & Golden LEC-133. Made from luxurious velvet for a rich  regal look and feel, these curtains feature a subtle grey and golden hue that adds a touch of sophistication to any home'},
  { "id": 19, "name": "2 PIECE OF PREMIUM VELVET CURTAINS BORDER DESIGN(BLUE & OFFWHITE)", "price": "6499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/19.jpg?alt=media&token=1940e4c4-6635-49ef-a72a-d559dfcedaf8" , description: '55×90″ (4.5×7 feet) each curtain Central Luxury Embossed With 2 folding belts' },
  { "id": 20, "name": "2 PIECE OF PREMIUM VELVET CURTAINS WITH 2 BELTS (BEIGE&GOLD)", "price": "7799", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/20.webp?alt=media&token=ff110342-7142-4425-a251-60cca101f254 " , description: '51×90″ (4.25×7.5 feet) each curtain Central Luxury Embossed With 2 folding belts' },
  { "id": 21, "name": "2 PCS LUXURY VELVET EMBROIDERED CURTAINS(DOUBLE SHADED) ", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/21.webp?alt=media&token=f730c64c-bcd6-4a63-9eb0-5ccfe683daf3" , description: '51×90″ (4.25×7.5 feet) each curtain Central Luxury Embossed With 2 folding belts ' },
  { "id": 22, "name": "Luxury Velvet Embroidered Curtains..", "price": "5999", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/22.webp?alt=media&token=5ea8b6b2-14d7-483f-970d-aca1810b1f01" , description: '51×90″ (4.25×7.5 feet) each curtain Central Luxury Embossed With 2 folding belts' },
  { "id": 23, "name": "2 Piece Of Premium Velvet Sprinkle Curtain-1639", "price": "6599", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/23.webp?alt=media&token=d837a16b-362f-4cfc-88bc-e3eb289e2966"  , description: ' 51×90″ (4.25×7.5 feet) each curtain Central Luxury Embossed With 2 folding belts'},
  { "id": 24, "name": "Luxury Velvet Splendid Curtains Blackout –Brown & Beige LEC-121", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/24.webp?alt=media&token=a6e04e71-d801-4104-9884-f8a04d33bd06"  , description: '55×90″ (4.5×7 feet) each curtain Central Luxury Embossed With 2 folding belts'},
  { "id": 25, "name": "Luxury Window Curtain Panel 03", "price": "3999", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/25.webp?alt=media&token=b72ffbd1-3d59-41f1-b8c7-8b3af394498c" , description: '51×90″ (4.25×7.5 feet) each curtain  Central Luxury Embossed With 2 folding belts' },
  { "id": 26, "name": "Luxury Velvet Curtain - Zinc And Off White", "price": "5999", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/26.webp?alt=media&token=eb85645a-d56c-4eae-b09a-9c835aa9ae87"  , description: '51×90″ (4.25×7.5 feet) each curtain Central Luxury Embossed With 2 folding belts'},
  { "id": 27, "name": "2 PIECE OF PREMIUM VELVET CURTAINS WITH 2 BELTS (BLACK&GOLD", "price": "7799", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/260.webp?alt=media&token=2273b4dd-589f-4615-a30f-6ff8b5e17aef"  , description: ' (2 Panels With 2 Belts ) 51×90″ (4.25×7.5 feet) each curtain Central Luxury Embossed With 2 folding belts'},
  { "id": 28, "name": "Luxury Velvet Splendid Curtains Blackout –Beige & Golden LEC-122", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/270.webp?alt=media&token=f9e1a1a5-4f61-410d-b340-2f0093f99b2e" , description: '90 Inches Long Size: 51×90″ (4.25×7.5 feet) 1 Pair. Super Velvet Curtain with design on top and on the belt.  Heavy Luxury Velvet Fabric Embroidered' },
  { "id": 29, "name": "Luxury Velvet Embroidered Curtains..", "price": "5999", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/27.webp?alt=media&token=f5767835-297a-4fb3-b23f-26768a232326"  , description: '90 Inches Long Size: 51×90″ (4.25×7.5 feet) 1 Pair. Super Velvet Curtain with design on top and on the belt.  Heavy Luxury Velvet Fabric Embroidered'},
  { "id": 30, "name": "2 Panels Luxury Velvet Embroidered Curtains With 2 (Brown & White)", "price": "6489", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/28.webp?alt=media&token=159d8998-1820-45a1-9916-dd6407ef06eb" , description: '90 Inches Long Size: 51×90″ (4.25×7.5 feet) 1 Pair. Super Velvet Curtain with design on top and on the belt.  Heavy Luxury Velvet Fabric Embroidered' },
  { "id": 31, "name": "Luxury Velvet Splendid Curtains Blackout – Navy Blue & White LEC-131", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/29.webp?alt=media&token=d653aa2b-e5dd-43b2-a31a-fc42553500d5" , description: '90 Inches Long Size: 51×90″ (4.25×7.5 feet) 1 Pair. Super Velvet Curtain with design on top and on the belt.  Heavy Luxury Velvet Fabric Embroidered' },
  { "id": 32, "name": "Luxury Velvet butterfly Curtains ( 2 Curtains Set )Blue LEC-109", "price": "6989", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/30.jpg?alt=media&token=35fa65e8-0916-4bc8-a574-0b66a5cc6c9d" , description: '51×90″ (4.25×7.5 feet) each Curtain, With 2 folding belts  Do Not Iron. Material: Velvet Elegant Comfort. Easy care machine washes and line dry. Luxury curtains set will provide you with quality and durability. Easily adjustable on 1 rod for easy fitting. Pair of Fully attractive jacquard-designed Curtains Ready-Made Curtains with Neat & Clean Stitching. Embossed design Heavy quality luxury velvet.' },
  { "id": 33, "name": "Luxury Embossed Velvet Curtains (2 Panels with 2 belts) Silver & Black LEC-107", "price": "6989", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/31.webp?alt=media&token=48f405ac-2d34-4fb9-a777-22d567628403" , description: '51×90″ (4.25×7.5 feet) each Curtain, With 2 folding belts  Do Not Iron. Material: Velvet Elegant Comfort. Easy care machine washes and line dry. Luxury curtains set will provide you with quality and durability. Easily adjustable on 1 rod for easy fitting. Pair of Fully attractive jacquard-designed Curtains Ready-Made Curtains with Neat & Clean Stitching. Embossed design Heavy quality luxury velvet.' },
  { "id": 34, "name": "Luxury Velvet Curtains Grey & Blue LEC-135", "price": "4899", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/32.webp?alt=media&token=e40d464e-5f42-4095-9fdb-8aae35df9601"  , description: '51×90″ (4.25×7.5 feet) each Curtain, With 2 folding belts  Do Not Iron. Material: Velvet Elegant Comfort. Easy care machine washes and line dry. Luxury curtains set will provide you with quality and durability. Easily adjustable on 1 rod for easy fitting. Pair of Fully attractive jacquard-designed Curtains Ready-Made Curtains with Neat & Clean Stitching. Embossed design Heavy quality luxury velvet.'},
  { "id": 35, "name": "Luxury Velvet Curtains Grey & Golden LEC-133", "price": "4899", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/33.webp?alt=media&token=b5b1c043-9884-4b50-97b1-1543064c9827" , description: '51×90″ (4.25×7.5 feet) each Curtain, With 2 folding belts  Do Not Iron. Material: Velvet Elegant Comfort. Easy care machine washes and line dry. Luxury curtains set will provide you with quality and durability. Easily adjustable on 1 rod for easy fitting. Pair of Fully attractive jacquard-designed Curtains Ready-Made Curtains with Neat & Clean Stitching. Embossed design Heavy quality luxury velvet.' },
  { "id": 36, "name": "Luxury Window Curtain Panel 04", "price": "3999", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/34.webp?alt=media&token=e62ea657-7da2-4e42-a8ed-e19f3dc7ae7e" , description: '51×90″ (4.25×7.5 feet) each Curtain, With 2 folding belts  Do Not Iron. Material: Velvet Elegant Comfort. Easy care machine washes and line dry. Luxury curtains set will provide you with quality and durability. Easily adjustable on 1 rod for easy fitting. Pair of Fully attractive jacquard-designed Curtains Ready-Made Curtains with Neat & Clean Stitching. Embossed design Heavy quality luxury velvet.' },
  { "id": 37, "name": "2 PIECE OF PREMIUM VELVET CURTAINS WITH 2 BELTS (BROWN&GOLD)", "price": "7790", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/35.webp?alt=media&token=2a181dd4-8161-49a4-b4be-1f9b0d56c05f" , description: 'Size: 51×90″(4.25×7.5 feet) each curtain With 2 belts Fabric: Premium Velvet Fabric Designed to give any space a luxurious look, our premium Velvet Blackout Curtains, are the ideal of elegance and functionality. Crafted from high-quality velvet fabric, these curtains provide a timeless charm while offering exceptional light-blocking capabilities.' },
  { "id": 38, "name": "Luxury Velvet Splendid Curtains Blackout ( 2 Curtain set )Gray LEC-116", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/36.webp?alt=media&token=7e8431b2-6df4-490b-9312-79cdc73dddd7" , description: 'Size: 51×90″ (4.25×7.5 feet) each curtain With 2 belts Fabric: Premium Velvet Fabric Designed to give any space a luxurious look, our premium Velvet Blackout Curtains, are the ideal of elegance and functionality. Crafted from high-quality velvet fabric, these curtains provide a timeless charm while offering exceptional light-blocking capabilities.' },
  { "id": 39, "name": "2 Piece Of Premium Velvet Sprinkle Curtain-1640", "price": "6599", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/37.webp?alt=media&token=021cedf1-03c3-46be-a854-959b671782f8" , description: 'Size: 51×90″(4.25×7.5 feet) each curtain With 2 belts Fabric: Premium Velvet Fabric Designed to give any space a luxurious look, our premium Velvet Blackout Curtains, are the ideal of elegance and functionality. Crafted from high-quality velvet fabric, these curtains provide a timeless charm while offering exceptional light-blocking capabilities.' },
  { "id": 40, "name": "2 PIECE OF PREMIUM VELVET CURTAINS BORDER DESIGN (ROYAL BLUE & OFFWHITE)", "price": "6499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/38.jpg?alt=media&token=885da829-0dd7-4d54-8dde-091f2a6c4020" , description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.'},
  { "id": 41, "name": "2 PIECE OF PREMIUM VELVET CURTAINS BORDER DESIGN (BROWN & OFFWHITE)", "price": "6499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/39.jpg?alt=media&token=d5119870-50bc-4d3e-baf4-98c1f129f98c", description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.' },
  { "id": 42, "name": "2 Piece Of Premium Velvet Sprinkle Curtain-1645", "price": "6599", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/40.webp?alt=media&token=ef08ccb9-e01d-4a28-ae84-09d8ad976f6e", description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.' },
  { "id": 43, "name": "2 Piece Of Premium Velvet Sprinkle Curtain-1644", "price": "6599", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/41.webp?alt=media&token=be88d459-b096-424e-b380-8cda14dd8e2b"  , description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.'},
  { "id": 44, "name": "2 PCS LUXURY VELVET EMBROIDERED CURTAINS(DOUBLE SHADED)", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/42.webp?alt=media&token=0841fa22-7ca5-42a3-be94-3641835007d2" , description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.'},
  { "id": 45, "name": "2 PIECE OF PREMIUM VELVET CURTAINS BORDER DESIGN (GREEN & OFFWHITE)", "price": "6499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/43.jpg?alt=media&token=2eaac2c1-a699-4d3a-83ed-3e8f6413aeb7" , description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.' },
  { "id": 46, "name": "Luxury Velvet Embroidered Curtains..", "price": "5999", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/44.webp?alt=media&token=d191176c-808e-4323-b10f-72adba4a739f" , description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.' },
  { "id": 47, "name": "2 Panels Luxury Velvet Embroidered Curtains With 2 Belts(Navy&offWhite)", "price": "5499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/45.webp?alt=media&token=291fab32-0aa7-43ec-98c1-5e78c984474f" , description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.' },
  { "id": 48, "name": "2 PIECE OF PREMIUM VELVET CURTAINS WITH 2 BELTS (RED&GOLD)", "price": "7799", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/46.webp?alt=media&token=c5d36d86-6d3a-479e-9a23-77b6bb6ce2bf" , description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.'},
  { "id": 49, "name": "Luxury Velvet Splendid Curtains Blackout – Beige & Black LEC-128", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/47.webp?alt=media&token=a4ad849a-cb8c-47fb-8ea0-e48910d27824" , description: 'Our 2-piece Luxury Plain Velvet Curtain is perfect for any room. Made with 100% machine-washable velvet, it offers a unique combination of sophistication. Made with 100% machine-washable velvet, it offers a unique combination of sophistication and functionality. Perfectly stitched, it can provide excellent noise reduction and insulation when hung. Available in grey, it will create a harmonious and stylish atmosphere in your home.'},
  { "id": 50, "name": "Luxury Velvet Splendid Curtains Blackout – Brown & White LEC-127", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/48.webp?alt=media&token=31d90e72-4e07-408c-89df-03b0173582b3" , description: '90 Inches Long Size: 51×90″ (4.25×7.5 feet) Color: golden color embroidery Central Luxury Embroidery With 2 folding belts Export Quality Material: Velvet  Easy care machine washes and line dry.  Easy care machine washes and line dry. Easy care machine washes and line dry. Ready-Made Curtains with Neat & Clean Stitching. Embossed design  Heavy quality luxury velvet.'},
  { "id": 51, "name": "Luxury Velvet Splendid Curtains Blackout ( 2 Curtain set )Cream LEC-120", "price": "7499", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/49.jpg?alt=media&token=f9fe95a6-7460-465d-82c0-9f0065d4e10b"  , description: '90 Inches Long Size: 51×90″ (4.25×7.5 feet) Color: golden color embroidery Central Luxury Embroidery With 2 folding belts Export Quality Material: Velvet  Easy care machine washes and line dry.  Easy care machine washes and line dry. Easy care machine washes and line dry. Ready-Made Curtains with Neat & Clean Stitching. Embossed design  Heavy quality luxury velvet.'},
  { "id": 52, "name": "Luxury Velvet butterfly Curtains ( 2 Curtains Set )Black LEC-108", "price": "6989", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/50.webp?alt=media&token=e2ac64e0-d3be-48b8-bb66-321a0acb95ab" , description: '90 Inches Long Size: 51×90″ (4.25×7.5 feet) Color: golden color embroidery Central Luxury Embroidery With 2 folding belts Export Quality Material: Velvet  Easy care machine washes and line dry.  Easy care machine washes and line dry. Easy care machine washes and line dry. Ready-Made Curtains with Neat & Clean Stitching. Embossed design  Heavy quality luxury velvet.' },
  { "id": 53, "name": "Luxury Embossed Velvet Curtains (2 Panels with 2 belts) Brown LEC-106", "price": "6989", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/51.jpg?alt=media&token=cf2bf09b-729a-4b41-a7d3-2fc995634989"  , description: '90 Inches Long Size: 51×90″ (4.25×7.5 feet) Color: golden color embroidery Central Luxury Embroidery With 2 folding belts Export Quality Material: Velvet  Easy care machine washes and line dry.  Easy care machine washes and line dry. Easy care machine washes and line dry. Ready-Made Curtains with Neat & Clean Stitching. Embossed design  Heavy quality luxury velvet.'},
  { "id": 54, "name": "2 Piece Of Premium Velvet Sprinkle Curtain-1641", "price": "6599", "image": "https://firebasestorage.googleapis.com/v0/b/furniture-storage.appspot.com/o/52.webp?alt=media&token=0806c8c2-ad78-44f3-a70e-8deed7738de4"  , description: '90 Inches Long Size: 51×90″ (4.25×7.5 feet) Color: golden color embroidery Central Luxury Embroidery With 2 folding belts Export Quality Material: Velvet  Easy care machine washes and line dry.  Easy care machine washes and line dry. Easy care machine washes and line dry. Ready-Made Curtains with Neat & Clean Stitching. Embossed design  Heavy quality luxury velvet.'}
];

function ProductDetail() {
  const { id } = useParams();
  const { addToCart } = useContext(CartContext);
  const product = products.find(p => p.id === parseInt(id));
  const similarItems = products.filter(p => p.id !== parseInt(id)).slice(0, 4);

  if (!product) {
    return <div>Product not found</div>;
  }

  return (
    <div className="container mx-auto py-8 px-4 pt-28">
      <div className="flex flex-col lg:flex-row items-start">
        {/* Image Section with Padding from Top */}
        <div className="lg:w-1/2 w-full mb-8 lg:mb-0 pr-4 pt-12"> {/* Added pt-12 for padding */}
          <Zoom>
            <img src={product.image} alt={product.name} className="w-full h-auto object-cover rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:scale-105" />
          </Zoom>
        </div>

        {/* Details Section */}
        <div className="lg:w-1/2 w-full pl-4">
        <h1 className="text-4xl font-bold text-gray-900 mb-4 pt-10">{product.name}</h1>

          <p className="text-2xl font-semibold text-green-600 mb-4">{product.price}</p>
          <p className="text-gray-700 mb-6">{product.description}</p>
          <button onClick={() => addToCart(product)} className="bg-green-500 text-white py-3 px-6 rounded-lg shadow-lg hover:bg-green-600 transition-all">
            Add to Cart
          </button>
        </div>
      </div>

      {/* Similar Items Section */}
      <div className="mt-12">
        <h2 className="text-3xl font-bold mb-6">Similar Items</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8">
          {similarItems.map(item => (
            <div key={item.id} className="border rounded-lg overflow-hidden shadow-lg hover:shadow-2xl transition-shadow duration-300">
              <img src={item.image} alt={item.name} className="w-full h-48 object-cover" />
              <div className="p-4 text-center">
                <h3 className="text-xl font-semibold text-gray-900 mb-2">{item.name}</h3>
                <p className="text-lg text-gray-600 mb-4">{item.price}</p>
                <Link to={`/product/${item.id}`}>
                  <button className="bg-green-500 text-white py-2 px-4 rounded-lg hover:bg-green-600 transition-all">
                    View Details
                  </button>
                </Link>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default ProductDetail;
